services:
  redis:
    image: XXX
    volumes:
        - type: XXX
          source: XXX
          target: XXX

  webapp:
    image: XXX
    volumes:
        - type: XXX
          source: XXX
          target: XXX
    ports:
        - "XXX:XXX"
    links:
        - "XXX:XXX"
    healthcheck:
        test: ["CMD", "curl", "--fail", "http://127.0.0.1:5000"]
        interval: XXX
    depends_on:
      - "XXX"

volumes:
  redis-vol:
    external: true
