FROM XXX

# Add missing commands
RUN apt-get XXX \
	&& apt-get install XXX \
	&& wget XXX \
	&& mkdir redis \
	&& XXX	\
	&& XXX \
	&& rm -rf redis \
	&& XXX

ENV XXX
WORKDIR XXX
RUN XXX
USER XXX
EXPOSE XXX
ENTRYPOINT XXX
