FROM XXX

WORKDIR XXX
ADD XXX redis.tar.gz
RUN mkdir XXX \
	&& tar XXX \
	&& apt-get XXX \
	&& apt-get install -y XXX \
	&& XXX \
	&& XXX \
	&& XXX \
	&& groupadd XXX \
	&& useradd XXX

ENV XXX
WORKDIR XXX
RUN chown XXX
USER XXX
EXPOSE XXX
ENTRYPOINT [XXX, "--protected-mode", "no", "--save", "5", "1"]
