FROM XXX

WORKDIR XXX
ADD XXX redis.tar.gz
RUN apt-get update \
	&& mkdir redis \
	&& tar XXX \
	&& apt-get install -y XXX \
	&& XXX \
	&& XXX \
	&& XXX \
	&& groupadd XXX \
	&& useradd XXX

ENV XXX
WORKDIR XXX
RUN chown XXX
USER XXX
EXPOSE XXX
ENTRYPOINT [XXX, "--protected-mode", "no","--save", "5", "1"]
